<?php
/**
 * DistributionApi
 * PHP version 7
 *
 * @category Class
 * @package  EspadaV8\PHPFlagr
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Flagr
 *
 * Flagr is a feature flagging, A/B testing and dynamic configuration microservice
 *
 * OpenAPI spec version: 1.0.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace EspadaV8\PHPFlagr\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use EspadaV8\PHPFlagr\ApiException;
use EspadaV8\PHPFlagr\Configuration;
use EspadaV8\PHPFlagr\HeaderSelector;
use EspadaV8\PHPFlagr\ObjectSerializer;

/**
 * DistributionApi Class Doc Comment
 *
 * @category Class
 * @package  EspadaV8\PHPFlagr
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DistributionApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation findDistributions
     *
     * @param  int $flagID numeric ID of the flag (required)
     * @param  int $segmentID numeric ID of the segment (required)
     *
     * @throws \EspadaV8\PHPFlagr\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \EspadaV8\PHPFlagr\Model\Distribution[]
     */
    public function findDistributions($flagID, $segmentID)
    {
        list($response) = $this->findDistributionsWithHttpInfo($flagID, $segmentID);
        return $response;
    }

    /**
     * Operation findDistributionsWithHttpInfo
     *
     * @param  int $flagID numeric ID of the flag (required)
     * @param  int $segmentID numeric ID of the segment (required)
     *
     * @throws \EspadaV8\PHPFlagr\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \EspadaV8\PHPFlagr\Model\Distribution[], HTTP status code, HTTP response headers (array of strings)
     */
    public function findDistributionsWithHttpInfo($flagID, $segmentID)
    {
        $returnType = '\EspadaV8\PHPFlagr\Model\Distribution[]';
        $request = $this->findDistributionsRequest($flagID, $segmentID);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EspadaV8\PHPFlagr\Model\Distribution[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                default:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EspadaV8\PHPFlagr\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation findDistributionsAsync
     *
     *
     *
     * @param  int $flagID numeric ID of the flag (required)
     * @param  int $segmentID numeric ID of the segment (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function findDistributionsAsync($flagID, $segmentID)
    {
        return $this->findDistributionsAsyncWithHttpInfo($flagID, $segmentID)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation findDistributionsAsyncWithHttpInfo
     *
     *
     *
     * @param  int $flagID numeric ID of the flag (required)
     * @param  int $segmentID numeric ID of the segment (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function findDistributionsAsyncWithHttpInfo($flagID, $segmentID)
    {
        $returnType = '\EspadaV8\PHPFlagr\Model\Distribution[]';
        $request = $this->findDistributionsRequest($flagID, $segmentID);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'findDistributions'
     *
     * @param  int $flagID numeric ID of the flag (required)
     * @param  int $segmentID numeric ID of the segment (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function findDistributionsRequest($flagID, $segmentID)
    {
        // verify the required parameter 'flagID' is set
        if ($flagID === null || (is_array($flagID) && count($flagID) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $flagID when calling findDistributions'
            );
        }
        if ($flagID < 1) {
            throw new \InvalidArgumentException('invalid value for "$flagID" when calling DistributionApi.findDistributions, must be bigger than or equal to 1.');
        }

        // verify the required parameter 'segmentID' is set
        if ($segmentID === null || (is_array($segmentID) && count($segmentID) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $segmentID when calling findDistributions'
            );
        }
        if ($segmentID < 1) {
            throw new \InvalidArgumentException('invalid value for "$segmentID" when calling DistributionApi.findDistributions, must be bigger than or equal to 1.');
        }


        $resourcePath = '/flags/{flagID}/segments/{segmentID}/distributions';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($flagID !== null) {
            $resourcePath = str_replace(
                '{' . 'flagID' . '}',
                ObjectSerializer::toPathValue($flagID),
                $resourcePath
            );
        }
        // path params
        if ($segmentID !== null) {
            $resourcePath = str_replace(
                '{' . 'segmentID' . '}',
                ObjectSerializer::toPathValue($segmentID),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation putDistributions
     *
     * @param  int $flagID numeric ID of the flag (required)
     * @param  int $segmentID numeric ID of the segment (required)
     * @param  \EspadaV8\PHPFlagr\Model\PutDistributionsRequest $body array of distributions (required)
     *
     * @throws \EspadaV8\PHPFlagr\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \EspadaV8\PHPFlagr\Model\Distribution[]
     */
    public function putDistributions($flagID, $segmentID, $body)
    {
        list($response) = $this->putDistributionsWithHttpInfo($flagID, $segmentID, $body);
        return $response;
    }

    /**
     * Operation putDistributionsWithHttpInfo
     *
     * @param  int $flagID numeric ID of the flag (required)
     * @param  int $segmentID numeric ID of the segment (required)
     * @param  \EspadaV8\PHPFlagr\Model\PutDistributionsRequest $body array of distributions (required)
     *
     * @throws \EspadaV8\PHPFlagr\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \EspadaV8\PHPFlagr\Model\Distribution[], HTTP status code, HTTP response headers (array of strings)
     */
    public function putDistributionsWithHttpInfo($flagID, $segmentID, $body)
    {
        $returnType = '\EspadaV8\PHPFlagr\Model\Distribution[]';
        $request = $this->putDistributionsRequest($flagID, $segmentID, $body);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EspadaV8\PHPFlagr\Model\Distribution[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                default:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\EspadaV8\PHPFlagr\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation putDistributionsAsync
     *
     *
     *
     * @param  int $flagID numeric ID of the flag (required)
     * @param  int $segmentID numeric ID of the segment (required)
     * @param  \EspadaV8\PHPFlagr\Model\PutDistributionsRequest $body array of distributions (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function putDistributionsAsync($flagID, $segmentID, $body)
    {
        return $this->putDistributionsAsyncWithHttpInfo($flagID, $segmentID, $body)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation putDistributionsAsyncWithHttpInfo
     *
     *
     *
     * @param  int $flagID numeric ID of the flag (required)
     * @param  int $segmentID numeric ID of the segment (required)
     * @param  \EspadaV8\PHPFlagr\Model\PutDistributionsRequest $body array of distributions (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function putDistributionsAsyncWithHttpInfo($flagID, $segmentID, $body)
    {
        $returnType = '\EspadaV8\PHPFlagr\Model\Distribution[]';
        $request = $this->putDistributionsRequest($flagID, $segmentID, $body);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'putDistributions'
     *
     * @param  int $flagID numeric ID of the flag (required)
     * @param  int $segmentID numeric ID of the segment (required)
     * @param  \EspadaV8\PHPFlagr\Model\PutDistributionsRequest $body array of distributions (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function putDistributionsRequest($flagID, $segmentID, $body)
    {
        // verify the required parameter 'flagID' is set
        if ($flagID === null || (is_array($flagID) && count($flagID) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $flagID when calling putDistributions'
            );
        }
        if ($flagID < 1) {
            throw new \InvalidArgumentException('invalid value for "$flagID" when calling DistributionApi.putDistributions, must be bigger than or equal to 1.');
        }

        // verify the required parameter 'segmentID' is set
        if ($segmentID === null || (is_array($segmentID) && count($segmentID) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $segmentID when calling putDistributions'
            );
        }
        if ($segmentID < 1) {
            throw new \InvalidArgumentException('invalid value for "$segmentID" when calling DistributionApi.putDistributions, must be bigger than or equal to 1.');
        }

        // verify the required parameter 'body' is set
        if ($body === null || (is_array($body) && count($body) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $body when calling putDistributions'
            );
        }

        $resourcePath = '/flags/{flagID}/segments/{segmentID}/distributions';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($flagID !== null) {
            $resourcePath = str_replace(
                '{' . 'flagID' . '}',
                ObjectSerializer::toPathValue($flagID),
                $resourcePath
            );
        }
        // path params
        if ($segmentID !== null) {
            $resourcePath = str_replace(
                '{' . 'segmentID' . '}',
                ObjectSerializer::toPathValue($segmentID),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;
        if (isset($body)) {
            $_tempBody = $body;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'PUT',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
