<?php
/**
 * EvalContextTest
 *
 * PHP version 7
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Flagr
 *
 * Flagr is a feature flagging, A/B testing and dynamic configuration microservice
 *
 * OpenAPI spec version: 1.0.0
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * EvalContextTest Class Doc Comment
 *
 * @category    Class
 * @description EvalContext
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class EvalContextTest extends \PHPUnit\Framework\TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "EvalContext"
     */
    public function testEvalContext()
    {
    }

    /**
     * Test attribute "entity_id"
     */
    public function testPropertyEntityId()
    {
    }

    /**
     * Test attribute "entity_type"
     */
    public function testPropertyEntityType()
    {
    }

    /**
     * Test attribute "entity_context"
     */
    public function testPropertyEntityContext()
    {
    }

    /**
     * Test attribute "enable_debug"
     */
    public function testPropertyEnableDebug()
    {
    }

    /**
     * Test attribute "flag_id"
     */
    public function testPropertyFlagId()
    {
    }
}
